flowchart LR
    A["Diffuse astrocytoma /<br/>Anaplastic astrocytoma /<br/>GBM IDH-mutant"] --> X["Astrocytoma,<br/>IDH-mutant<br/>grade 2/3/4"]
    B["Anaplastic<br/>oligodendroglioma"] --> Y["Oligodendroglioma,<br/>IDH-mut, 1p/19q-codel<br/>grade 2/3"]
    C["Glioblastoma<br/>IDH-wildtype"] --> Z["Glioblastoma,<br/>IDH-wildtype<br/>grade 4"]