flowchart LR
  L1["NETC<br/>label 1"] --> TC["TC<br/>Tumor Core"]
  L3["ET<br/>label 3"] --> TC
  L3 --> ETR["ET region"]
  L2["SNFH<br/>label 2"] --> WT["WT<br/>Whole Tumor"]
  TC --> WT
  L4["RC<br/>label 4"] --> RCR["RC region<br/>scored alone"]